language: node_js
node_js:
  - "lts/*"
git:
  depth: false
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
deploy:
  provider: npm
  email: "$NPM_USER"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
  
